name: Deploy

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  manual_approval:
    runs-on: ubuntu-latest
    outputs:
      props: ${{ steps.set_output.outputs }}
    steps:
      - id: set_output
        name: Set Output
        run: echo "::set-output name=props::approve"
      - name: Manual Approval
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: wei/github-approval-action@v2
        with:
          token: ${{ github.TOKEN }}

  EC2-Deploy:
    runs-on: ubuntu-latest
    needs: manual_approval
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.deploy.outputs.vm_url }}
    steps:
      - id: deploy
        name: Deploy
        uses: bitovi/github-actions-deploy-docker-to-ec2@v0.4.6
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
          aws_default_region: us-east-1

          app_port: 3000
