name: Deploy

on:
  pull_request:
    types: closed

permissions:
  contents: read

jobs:
  approved:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR was merged. Deploying to AWS now!"

  EC2-Deploy:
    runs-on: ubuntu-latest
    needs: approved
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.deploy.outputs.vm_url }}
    steps:
      - id: deploy
        name: Deploy
        uses: bitovi/github-actions-deploy-docker-to-ec2@v0.4.6
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
          aws_default_region: us-east-1

          app_port: 3000
