name: Deploy

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  deploy-aproval:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: juliocesardemoraes
      - name: Deploy to production
        run: echo deploy confirmed

  EC2-Deploy:
    runs-on: ubuntu-latest
    needs: deploy-aproval
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.deploy.outputs.vm_url }}
    steps:
      - id: deploy
        name: Deploy
        uses: bitovi/github-actions-deploy-docker-to-ec2@v0.4.6
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
          aws_default_region: us-east-1

          app_port: 3000
